name: Spring Boot Continuous Integration
on:
  push:
    paths:
      - "sb-mma/**"
      - ".github/**/java*.yml"
    branches:
      - main

env:
  PROJECT_DIRECTORY: "sb-mma"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Run docker compose
        working-directory: ${{env.PROJECT_DIRECTORY}}
        run: docker-compose up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Grant execute permission to mvnw
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: chmod +x mvnw

      - name: Build and run Unit/Integration Tests with Maven
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: ./mvnw --no-transfer-progress clean verify
